### ISSUE TITLE
LTC6802-2 liefert plausible Werte aber eingefroren

### ISSUE THREAD

**Issue by jontubs** [PowerStat/LTC6802#1]
Hallo,

ersteinmal möchte ich mich für die saubere Umsetzung der Library bedanken. Saubere Arbeit.

Ich habe allerdings auf einem Arduino Nano so ein bisschen Schwierigkeiten damit. 
Ich führe genau dein Beispiel aus der Library aus und kommen auch plausible Daten aus dem LTC, aber die Werte verändern sich nicht.

![LT6802 klemmt](https://user-images.githubusercontent.com/38430505/108263641-d2131180-7166-11eb-8459-89433e8ab1fa.png)
 
Der LTC scheint irgendwie zu hängen, denn die Temperatur verändert sich nicht. 

![photo_2021-02-17_21-27-52](https://user-images.githubusercontent.com/38430505/108263891-1acaca80-7167-11eb-96fc-d2d9d82ac1fe.jpg)

Der Aufbau ist relativ sauber auf einer gefertigten Platine mit 10k Pullup Widerständen an MOSI und MISO und keine Widerstände an Clock und Chipselect. 

Hast du mal ein ähnliches Verhalten mit dem LTC6802-2 gehabt?

**Comment by PowerStat** [comment]
Hab selbst leider nur zwei LTC6802-1 hier. Hatte damals mal ein Schüler aus Österreich getestet. Leider ist da der Kontakt verloren gegangen. Die LTC6802 werden scheinbar auch nicht mehr produziert. Aktuell scheinen wohl die LTC6803 zu sein.
Wir hatten da nur mit UNO's gearbeitet - Nano haben wir leider nie probiert.
Kann aber auch gut sein, das ich in der Spezifikation was übersehen habe - die ist an einigen Stellen wirklich schwierig zu verstehen. Falls Du was rausfindest besser ich da gerne nach.

Halt stop, das hatten wir doch - schau mal ins Beispiel:

chip1.cfgWrite(false);          // Write configuration back to chip, because chip resets these every 2.5s when nothing happens on SPI

Setz doch mal das delay auf 2000 runter,

**Comment by jontubs** [comment]
Fehler gefunden, bei Luftverdrahtung muss man ein bisschen den SPI-Takt senken. Der Chip kann zwar ein 1Mhz SPI, aber die Signale werden bei Luftverdrahtung dann entsprechend rund.

SPI.setClockDivider(SPI_CLOCK_DIV64); statt den 16er teiler und jetzt gehts.

**Comment by PowerStat** [comment]
Super :)
